kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ubi-quarkus-native-s2i
  labels:
    app: api-backend
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 19.2.0.1
      annotations:
        openshift.io/imported-from: 'quay.io/quarkus/ubi-quarkus-native-s2i:19.2.0.1'
      from:
        kind: DockerImage
        name: 'quay.io/quarkus/ubi-quarkus-native-s2i:19.2.0.1'
      importPolicy: {}
      referencePolicy:
        type: Source
